"""Change user to file relationship to many to many

Revision ID: 26874bb83c47
Revises: b9df168d74ec
Create Date: 2022-01-26 00:46:26.981333

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26874bb83c47'
down_revision = 'b9df168d74ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FileAssociation',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_status', sa.String(length=50), nullable=False),
    sa.Column('file_status', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['File.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User_Info.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'file_id')
    )
    op.drop_constraint('File_ibfk_1', 'File', type_='foreignkey')
    op.drop_column('File', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('File', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('File_ibfk_1', 'File', 'User_Info', ['user_id'], ['id'])
    op.drop_table('FileAssociation')
    # ### end Alembic commands ###
