"""added headline column

Revision ID: fba340536cca
Revises: 92397c862483
Create Date: 2022-01-02 22:09:55.169780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fba340536cca"
down_revision = "92397c862483"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "User_Info", sa.Column(
            "headline", sa.String(length=250), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User_Info", "headline")
    # ### end Alembic commands ###
