"""Add joined date for user table

Revision ID: 073ab15e6dcf
Revises: 347748a03c6a
Create Date: 2022-02-11 21:02:21.895015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '073ab15e6dcf'
down_revision = '347748a03c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User_Info', sa.Column('joined', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User_Info', 'joined')
    # ### end Alembic commands ###
