"""Add request status to file association table

Revision ID: 456998b7e55a
Revises: c69dd6026939
Create Date: 2022-02-03 18:50:26.933725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "456998b7e55a"
down_revision = "c69dd6026939"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "FileAssociation",
        sa.Column("request_status", sa.String(length=25), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("FileAssociation", "request_status")
    # ### end Alembic commands ###
