"""Add last_modified to File

Revision ID: 902349b041a9
Revises: a63fddba4104
Create Date: 2022-01-20 23:41:01.996801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902349b041a9'
down_revision = 'a63fddba4104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('File', sa.Column('last_modified', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('File', 'last_modified')
    # ### end Alembic commands ###
