"""Add user_id to feedback table

Revision ID: b28f37c70929
Revises: 77e7a228a6bd
Create Date: 2022-01-30 02:59:01.668426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b28f37c70929'
down_revision = '77e7a228a6bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Feedback', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Feedback', 'User_Info', ['user_id'], ['id'])
    op.create_foreign_key(None, 'File', 'User_Info', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'File', type_='foreignkey')
    op.drop_constraint(None, 'Feedback', type_='foreignkey')
    op.drop_column('Feedback', 'user_id')
    # ### end Alembic commands ###
