"""move file_status to file table

Revision ID: c69dd6026939
Revises: 9ee9b24b0079
Create Date: 2022-02-03 18:47:37.828996

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "c69dd6026939"
down_revision = "9ee9b24b0079"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "File", sa.Column("file_status", sa.String(length=25), nullable=False)
    )
    op.drop_column("FileAssociation", "file_status")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "FileAssociation",
        sa.Column("file_status", mysql.VARCHAR(length=25), nullable=False),
    )
    op.drop_column("File", "file_status")
    # ### end Alembic commands ###
